### ISSUE TITLE
Can we send different data to different windows?

### ISSUE THREAD

**Issue by raghupviyer** [pvrobays/electron-multi-monitor-react#1]
Suppose I click a button on the main window, will I be able to send different data on the different windows at the same time instead of sending the same data to all the windows?

Also, can each window be full-screen on different monitors by default?

**Comment by pvrobays** [comment]
hi @raghupviyer 

Yes, that's definitely possible. Once the monitors have been set up, you can choose what parts are on which monitor and how they react.

In fact, when you click a button it's just handled by React. So in the example case I chose to adapt all the other monitors, but that's completely up to you.

The windows can be set to full-screen. It's an electron app so you can see [here](https://www.electronjs.org/docs/latest/api/browser-window#winsetfullscreenflag) how that's done.
I could look for add an API which exposes this full screen feature, but that would probably be an option to 'set all windows full screen'. It's quite hard to design a decent working API. But if you have suggestions, feel free to share them!

**Comment by raghupviyer** [comment]
ok Thanks a lot for your help ... 👍
